Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,314 +1,214 @@
-# Can be used locally with https://github.com/nektos/act
-# Note the XXX line below.
+name: build
 
-name: BuildTest
 on:
-  pull_request:
   workflow_dispatch:
-  push:
-    branches:
-      - master
+    inputs:
+      test_build:
+        description: 'Test build'
+        required: false
+        default: 'false'
+        type: choice
+        options:
+        - true
+        - false
+      fake_build:
+        description: 'Fake build'
+        required: false
+        default: 'false'
+        type: choice
+        options:
+        - true
+        - false
+      suffix:
+        description: 'TAG suffix'
+        required: false
+        default: ''
+        type: string
+
+env:
+  TEST_BUILD: ${{ github.event.inputs.test_build == 'true' }}
+  FAKE_BUILD: ${{ github.event.inputs.fake_build == 'true' }}
+  TAG_SUFFIX: ${{ github.event.inputs.suffix }}
+  REPO_URL: https://github.com/openwrt-xiaomi/dropbear
+  REPO_LNK: openwrt-xiaomi/dropbear
+  REPO_BRANCH: master
+  TAG_PREFIX: v
+  TC_DIR: ${{ github.workspace }}/tc
+  TC_LNK: https://toolchains.bootlin.com/downloads/releases/toolchains
+  TZ: UTC
+  BUILD_DATE: unknown
+  REPO_DATE: unknown
+
 jobs:
-  build:
-    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
-    strategy:
-      matrix:
-        # XXX uncomment the line below to work with act, see https://github.com/nektos/act/issues/996
-        # name: []
-
-        # Rather than a boolean False we use eg
-        #   runcheck: 'no'
-        # Otherwise GH expressions will make a None var
-        # compare with False. We want an undefined default of True.
-
-        # MULTI and NOWRITEV are passed as integers to the build
-        include:
-          - name: plain linux
-            upload_sizes: 1
-
-          - name: multi binary
-            multi: 1
-            multilink: 1
-
-          - name: multi binary, dropbearmulti argv0
-            multi: 1
-            multiwrapper: 1
-
-          - name: client only
-            runcheck: 'no'
-            make_target: PROGRAMS=dbclient
-
-          - name: server only
-            runcheck: 'no'
-            make_target: PROGRAMS=dropbear
-
-          - name: bundled libtom, 22.04, no writev()
-            # test can use an older distro with bundled libtommath
-            os: ubuntu-22.04
-            configure_flags: --enable-bundled-libtom --enable-werror
-            # NOWRITEV is unrelated, test here to save a job
-            nowritev: 1
-            # our tests expect >= python3.7
-            runcheck: 'no'
-
-          - name: linux clang
-            cc: clang
-
-          # Some platforms only have old compilers, we try to keep
-          # compatibilty. For some reason -std=c89 doesn't enforce
-          # early declarations so we specify it anyway.
-          - name: c89
-            extracflags: -std=c89 -Wdeclaration-after-statement
-            # enable all options
-            nondefault: 1
-            configure_flags: --enable-pam
-            # sntrup761.c is not c89 compliant
-            localoptions: |
-              #define DROPBEAR_SNTRUP761 0
-              #define DROPBEAR_MLKEM768 0
-
-          - name: macos 14
-            os: macos-14
-            cc: clang
-            # OS X says daemon() and utmp are deprecated.
-            # OS X tests for undefined TARGET_OS_EMBEDDED in libc headers
-            extracflags: -Wno-deprecated-declarations -Wno-undef
-            runcheck: 'no'
-            apt: 'no'
-            # fails with:
-            # .../ranlib: file: libtomcrypt.a(cbc_setiv.o) has no symbols
-            ranlib: ranlib -no_warning_for_no_symbols
-
-          - name: macos 15
-            os: macos-15
-            cc: clang
-            # OS X says daemon() and utmp are deprecated.
-            # OS X tests for undefined TARGET_OS_EMBEDDED in libc headers
-            extracflags: -Wno-deprecated-declarations -Wno-undef
-            runcheck: 'no'
-            apt: 'no'
-            # fails with:
-            # .../ranlib: file: libtomcrypt.a(cbc_setiv.o) has no symbols
-            ranlib: ranlib -no_warning_for_no_symbols
-
-          # Check that debug code doesn't bitrot
-          - name: DEBUG_TRACE
-            nondefault: 1
-            configure_flags: --enable-pam
-            localoptions: |
-              #define DEBUG_TRACE 5
-
-          # Check off-by-default options don't bitrot
-          - name: nondefault options
-            nondefault: 1
-            configure_flags: --enable-pam
-
-          - name: most options disabled
-            configure_flags: --disable-harden --disable-zlib --disable-openpty --disable-lastlog
-            runcheck: 'no'
-            localoptions: |
-              #define DROPBEAR_RSA 0
-              #define INETD_MODE 0
-              #define DROPBEAR_REEXEC 0
-              #define DROPBEAR_SMALL_CODE 0
-              #define DROPBEAR_CLI_LOCALTCPFWD 0
-              #define DROPBEAR_CLI_REMOTETCPFWD 0
-              #define DROPBEAR_SVR_LOCALTCPFWD 0
-              #define DROPBEAR_SVR_REMOTETCPFWD 0
-              #define DROPBEAR_SVR_AGENTFWD 0
-              #define DROPBEAR_CLI_AGENTFWD 0
-              #define DROPBEAR_CLI_PROXYCMD 0
-              #define DROPBEAR_USER_ALGO_LIST 0
-              #define DROPBEAR_AES128 0
-              #define DROPBEAR_AES256 0
-              #define DROPBEAR_ENABLE_CTR_MODE 0
-              #define DROPBEAR_SHA1_HMAC 0
-              #define DROPBEAR_SHA2_256_HMAC 0
-              #define DROPBEAR_RSA 0
-              #define DROPBEAR_ECDSA 0
-              #define DROPBEAR_SK_KEYS 0
-              #define DROPBEAR_DELAY_HOSTKEY 0
-              #define DROPBEAR_DH_GROUP14_SHA1 0
-              #define DROPBEAR_DH_GROUP14_SHA256 0
-              #define DROPBEAR_ECDH 0
-              #define DROPBEAR_DH_GROUP1_CLIENTONLY 0
-              #define DO_MOTD 0
-              #define DROPBEAR_SVR_PUBKEY_AUTH 0
-              #define DROPBEAR_CLI_PASSWORD_AUTH 0
-              #define DROPBEAR_CLI_PUBKEY_AUTH 0
-              #define DROPBEAR_USE_PASSWORD_ENV 0
-              #define DROPBEAR_SFTPSERVER 0
-
-          - name: no sha1
-            runcheck: 'no'
-            # disables all sha1
-            localoptions: |
-              #define DROPBEAR_SHA1_HMAC 0
-              #define DROPBEAR_RSA_SHA1 0
-              #define DROPBEAR_DH_GROUP14_SHA1 0
-              #define DROPBEAR_ECDSA 0
-              #define DROPBEAR_ED25519 0
-              #define DROPBEAR_SK_KEYS 0
-              #define DROPBEAR_ENABLE_GCM_MODE 1
-              #define DROPBEAR_3DES 1
-              #define DROPBEAR_DH_GROUP16 1
-              #define DROPBEAR_SHA2_512_HMAC 1
-              #define DROPBEAR_CLI_PUBKEY_AUTH 0
-
-          - name: pq, no plain x25519
-            localoptions: |
-              #define DROPBEAR_CURVE25519 0
-
-          # # Fuzzers run standalone. A bit superfluous with cifuzz, but
-          # # good to run the whole corpus to keep it working.
-          # - name: fuzzing with address sanitizer
-          #   configure_flags: --enable-fuzz --disable-harden --enable-bundled-libtom --enable-werror
-          #   ldflags: -fsanitize=address
-          #   extracflags: -fsanitize=address
-          #   # -fsanitize=address prevents aslr, don't test it
-          #   pytest_addopts: -k "not aslr"
-          #   fuzz: True
-          #   cc: clang
-
-          # # Undefined Behaviour sanitizer
-          # - name: fuzzing with undefined behaviour sanitizer
-          #   configure_flags: --enable-fuzz --disable-harden --enable-bundled-libtom --enable-werror
-          #   ldflags: -fsanitize=undefined
-          #   # don't fail with alignment due to https://github.com/libtom/libtomcrypt/issues/549
-          #   extracflags: -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize-recover=alignment
-          #   pytest_addopts: -k "not aslr"
-          #   fuzz: True
-          #   cc: clang
-
-    env:
-      MULTI: ${{ matrix.multi }}
-      CC: ${{ matrix.cc || 'gcc' }}
-      LDFLAGS: ${{ matrix.ldflags }}
-      EXTRACFLAGS: ${{ matrix.extracflags }}
-      CONFIGURE_FLAGS: ${{ matrix.configure_flags || '--enable-werror' }}
-      MAKE_TARGET: ${{ matrix.make_target }}
-      # for fuzzing
-      CXX: clang++
-      RANLIB: ${{ matrix.ranlib || 'ranlib' }}
-      # pytest in "make check" recognises this for extra arguments
-      PYTEST_ADDOPTS: ${{ matrix.pytest_addopts }}
-      # some pytests depend on special setup from this file. see authorized_keys below.
-      DBTEST_IN_ACTION: true
-      LOCALOPTIONS: ${{ matrix.localoptions }}
-
+  check:
+    runs-on: ubuntu-24.04
+    outputs:
+      tag: ${{ steps.gh.outputs.tag }}
+      date: ${{ steps.gh.outputs.date }}
+      sha: ${{ steps.gh.outputs.sha }}
+      url: ${{ steps.gh.outputs.url }}
+      message: ${{ steps.gh.outputs.message }}
+      build_date: ${{ steps.gh.outputs.build_date }}
+      build_time: ${{ steps.gh.outputs.build_time }}
+      fw_date: ${{ steps.gh.outputs.fw_date }}
+      test_build: ${{ env.TEST_BUILD }}
+      fake_build: ${{ env.FAKE_BUILD }}
     steps:
-      - name: deps
-        if: ${{ matrix.apt != 'no' }}
+      - name: Get repo data via GH API
+        id: gh
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          sudo apt-get -y update
-          sudo apt-get -y install zlib1g-dev libtomcrypt-dev libtommath-dev mercurial python3-venv libpam0g-dev $CC
-
-      - uses: actions/checkout@v4
-
-      - name: configure
+          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
+          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
+          BRANCH=$(gh api repos/$REPO_LNK --jq '.default_branch')
+          REPO_DATE=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.committer.date')
+          BUILD_DATE=$( date --utc +'%Y%m%d' )
+          BUILD_TIME=$( date --utc +'%H%M' )
+          FW_DATE=$( date --utc +'%Y-%m-%d' )
+          TAG=$TAG_PREFIX$BUILD_DATE-$BUILD_TIME
+          echo "TAG=$TAG" >> $GITHUB_ENV 
+          echo "REPO_DATE=$REPO_DATE" >> $GITHUB_ENV
+          {
+            echo "tag=$TAG"
+            echo "date=$(date --utc -d $REPO_DATE +%Y%m%d)"
+            echo "sha=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.sha[0:7]')"
+            echo "url=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.html_url')"
+            echo "message<<EOF"
+            gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.message'
+            echo EOF
+            echo "build_date=$BUILD_DATE"
+            echo "build_time=$BUILD_TIME"
+            echo "fw_date=$FW_DATE"
+          } >> $GITHUB_OUTPUT
+  
+  build:
+    needs: check
+    runs-on: ubuntu-24.04
+    strategy:
+      fail-fast: false
+      matrix:
+        arch:
+          - arm64
+          - armv7a
+          - armv5
+          - mips
+        isTestOrFake:
+          - ${{ needs.check.outputs.test_build == 'true' || needs.check.outputs.fake_build == 'true' }}
+        exclude:
+          - { isTestOrFake: true }
+    steps:
+      - name: Initialization environment
+        env:
+          DEBIAN_FRONTEND: noninteractive
         run: |
-          $CC --version || echo unknown $CC version
-          ./configure $CONFIGURE_FLAGS CFLAGS="-O2 -Wall -Wno-pointer-sign $EXTRACFLAGS" --prefix="$HOME/inst" || (cat config.log; exit 1)
-
-      - name: nowritev
-        if: ${{ matrix.nowritev }}
-        run: sed -i -e s/HAVE_WRITEV/DONT_HAVE_WRITEV/ config.h
-
-      - name: localoptions
+          sudo apt-get -qq update
+          #sudo apt-get -qq update && sudo apt-get -qq upgrade
+          sudo apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext
+          sudo apt-get -qq install git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev
+          sudo apt-get -qq install file wget libgmp3-dev libmpfr-dev libmpc-dev 
+          sudo apt-get -qq autoremove --purge
+          sudo apt-get -qq clean
+          sudo timedatectl set-timezone "$TZ"
+      
+      - name: Checkout sources
+        uses: actions/checkout@main
+      
+      - name: Download Toolchains
+        env:
+          ARCH: ${{ matrix.arch }}
         run: |
-          echo "$LOCALOPTIONS" | tee localoptions.h
-
-      - name: nondefault
-        if: ${{ matrix.nondefault }}
+          mkdir -p $TC_DIR
+          cd $TC_DIR
+          [ $ARCH = arm64  ] && PKG_NAME="aarch64"
+          [ $ARCH = armv7a ] && PKG_NAME="armv7-eabihf"
+          [ $ARCH = armv5  ] && PKG_NAME="armv5-eabi"
+          [ $ARCH = mips   ] && PKG_NAME="mips32el"
+          wget $TC_LNK/$PKG_NAME/tarballs/$PKG_NAME--musl--stable-2020.02-2.tar.bz2
+          tar -xf $PKG_NAME*.tar.bz2
+          TC_DIR=$TC_DIR/$PKG_NAME--musl--stable-2020.02-2
+          TARGET_HOST=$( find $TC_DIR -maxdepth 1 -type d -name '*-buildroot-*' | xargs -- basename )
+          GCC_PATH=$TC_DIR/bin          
+          CROSS_COMPILE=$TC_DIR/bin/$TARGET_HOST-
+          echo "TC_DIR=$TC_DIR" >> $GITHUB_ENV
+          echo "GCC_PATH=$GCC_PATH" >> $GITHUB_ENV
+          echo "TARGET_HOST=$TARGET_HOST" >> $GITHUB_ENV
+          echo "CROSS_TOOL=$GCC_PATH/$TARGET_HOST-" >> $GITHUB_ENV
+          echo "CROSS_COMPILE=$CROSS_COMPILE" >> $GITHUB_ENV
+      
+      - name: Build dropbear
+        id: compile
+        env: 
+          ARCH: ${{ matrix.arch }}
         run: |
-          # Turn on anything that's off by default. Rough but seems sufficient
-          grep ' 0$' src/default_options.h | sed 's/0$/1/' >> localoptions.h
-          # PAM clashes with password
-          echo "#define DROPBEAR_SVR_PASSWORD_AUTH 0" >> localoptions.h
-          # 1 second timeout is too short
-          sed -i "s/DEFAULT_IDLE_TIMEOUT 1/DEFAULT_IDLE_TIMEOUT 99/" localoptions.h
+          echo "############ prepare config ############"
+          ./configure --host=$TARGET_HOST --enable-static --disable-zlib --disable-harden \
+            --disable-pam --enable-bundled-libtom --enable-openpty --enable-syslog \
+            --disable-lastlog --disable-utmpx --disable-utmp --disable-wtmp --disable-wtmpx \
+            --disable-loginfunc --disable-pututline --disable-pututxline \
+            CC="${CROSS_TOOL}gcc" \
+            CFLAGS="-Os -Wl,-static -ffunction-sections -fdata-sections" \
+            LDFLAGS="-static -Wl,--gc-sections -Wl,--strip-all"
+          echo "############ compile ###################"
+          make PROGRAMS="dropbear scp dropbearkey" MULTI=1 STATIC=1
+          if [ ! -e "dropbearmulti" ]; then
+              echo "ERROR: File dropbearmulti not found!"
+              exit 1
+          fi
+          OUT_DIR=outbin
+          mkdir -p $OUT_DIR
+          cp -f dropbearmulti $OUT_DIR/
+          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV
+          echo "status=success" >> $GITHUB_OUTPUT
 
-      - name: make
-        run: |
-          cat localoptions.h
-          make -j3 $MAKE_TARGET
-
-      - name: multilink
-        if: ${{ matrix.multilink }}
-        run: make multilink
-
-      - name: multi wrapper script
-        if: ${{ matrix.multiwrapper }}
-        run: |
-          cp .github/multiwrapper dropbear
-          cp .github/multiwrapper dbclient
-          cp .github/multiwrapper dropbearkey
-          cp .github/multiwrapper dropbearconvert
-
-      - name: makefuzz
-        run: make fuzzstandalone
-        if: ${{ matrix.fuzz }}
-
-        # avoid concurrent install, osx/freebsd is racey (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208093)
-      - name: make install
-        run: make install
-
-      - name: keys
-        if: ${{ matrix.runcheck != 'no' }}
-        run: |
-          mkdir -p ~/.ssh
-          # remove old files so we can rerun in-place with "act -r" during test development
-          rm -vf ~/.ssh/id_dropbear*
-          ~/inst/bin/dropbearkey -t ecdsa -f ~/.ssh/id_dropbear | grep ^ecdsa > ~/.ssh/authorized_keys
-          # Convert to openssh format so that asyncssh can find it in tests
-          ~/inst/bin/dropbearconvert dropbear openssh ~/.ssh/id_dropbear ~/.ssh/id_ecdsa
-
-          # to test setting SSH_PUBKEYINFO, replace the trailing comment
-          ~/inst/bin/dropbearkey -t ecdsa -f ~/.ssh/id_dropbear_key2 | grep ^ecdsa | sed 's/[^ ]*$/key2 extra/' >> ~/.ssh/authorized_keys
-          ~/inst/bin/dropbearkey -t ecdsa -f ~/.ssh/id_dropbear_key3 | grep ^ecdsa | sed 's/[^ ]*$/key3%char/' >> ~/.ssh/authorized_keys
-          ~/inst/bin/dropbearkey -t ecdsa -f ~/.ssh/id_dropbear_key4 | grep ^ecdsa | sed 's/[^ ]*$/key4,char/' >> ~/.ssh/authorized_keys
-          chmod 700 ~ ~/.ssh ~/.ssh/authorized_keys
-          ls -ld ~ ~/.ssh ~/.ssh/authorized_keys
-
-      - name: binary size
-        run: size dropbear dbclient | tee -a sizes.txt
-
-        # upload config.log if something has failed
-      - name: config.log
-        if: ${{ !env.ACT && (failure() || cancelled()) }}
-        uses: actions/upload-artifact@v4
+      - name: Upload OUT directory
+        uses: actions/upload-artifact@main
+        if: steps.compile.outputs.status == 'success'
+        env: 
+          ARCH: ${{ matrix.arch }}
         with:
-          name: config.log
-          path: config.log
+          name: dropbearmulti-${{ env.ARCH }}
+          path: ${{ github.workspace }}/${{ env.OUT_DIR }}
+          if-no-files-found: error 
 
-      - name: upload sizes
-        if: ${{ matrix.upload_sizes }}
-        uses: actions/upload-artifact@v4
+  release:
+    needs: [ check, build ]
+    permissions:
+      contents: write
+    runs-on: ubuntu-24.04
+    strategy:
+      max-parallel: 1
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
         with:
-          name: sizes.txt
-          path: sizes.txt
+          pattern: dropbearmulti-*
 
-      - name: check
-        if: ${{ matrix.runcheck != 'no' }}
-        run: make check
+      - name: Put images into zip
+        env:
+          TAG: ${{ needs.check.outputs.tag }}
+        run: |
+          ls -la
+          mkdir -p public
+          for XDIR in ./dropbearmulti-*; do
+              if [ -d "$XDIR" ]; then
+                  NAME=$( basename $XDIR )
+                  ARCH=$( echo $NAME | cut -d- -f2 )
+                  cp $XDIR/dropbearmulti ./public/dropbearmulti_$ARCH
+              fi
+          done
+          find ./public -type f -name 'dropbearmulti_*' -exec sh -c 'zip -0 ./public/dropbearmulti-$TAG.zip -j {} {}/*' \;
 
-      # Sanity check that the binary runs
-      - name: genrsa
-        if: ${{ matrix.runcheck != 'no' }}
-        run: ~/inst/bin/dropbearkey -t rsa -f testrsa
-      - name: genecdsa256
-        if: ${{ matrix.runcheck != 'no' }}
-        run: ~/inst/bin/dropbearkey -t ecdsa -f testec256 -s 256
-      - name: genecdsa384
-        if: ${{ matrix.runcheck != 'no' }}
-        run: ~/inst/bin/dropbearkey -t ecdsa -f testec384 -s 384
-      - name: genecdsa521
-        if: ${{ matrix.runcheck != 'no' }}
-        run: ~/inst/bin/dropbearkey -t ecdsa -f testec521 -s 521
-      - name: gened25519
-        if: ${{ matrix.runcheck != 'no' }}
-        run: ~/inst/bin/dropbearkey -t ed25519 -f tested25519
-
-      - name: fuzz
-        if: ${{ matrix.fuzz }}
-        run: ./fuzzers_test.sh
+      - name: Upload assets
+        uses: andelf/nightly-release@main
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TAG: ${{ needs.check.outputs.tag }}
+        with:
+          prerelease: false
+          tag_name: ${{ needs.check.outputs.tag }}${{ env.TAG_SUFFIX }}
+          name: '${{ needs.check.outputs.tag }}'
+          body: |
+            dropbearmulti for XMiR-Patcher ${{ needs.check.outputs.build_date }}-${{ needs.check.outputs.build_time }}
+            author: [remittor](https://github.com/remittor)
+          files: ./public/*.zip
